from django.urls import path
from . import views
from django.conf import settings
from django.contrib import admin



urlpatterns = [
    path('home/', views.home),
    path('income/', views.income_view, name = 'register_income'),
    path('registerincomes/', views.registerincomes),
    path('academy/', views.academy),
    path('home/academy', views.academy),
    path('feed/', views.feed),
    path('home/feed', views.feed),
    path('home/academy/QueSonFP', views.QueSonFP),
    path('home/academy/ObjetivosFP', views.ObjetivosFP),
    path('home/academy/ElementosFP', views.ElementosFP),
    path('home/academy/OptimizarFP', views.OptimizarFP),
    path('home/academy/QueSonGH', views.QueSonGH),
    path('home/notifications',views.notifications),
    path('home/notifications/advices',views.advices),
    path('home/notifications/reminders',views.reminders),
    path('home/notifications/dues',views.dues),
    path('spent/', views.spent_view, name = 'register_spent'),
    path('income/deleteincome/<codigo>', views.deleteincome),
    path('income/editincome/<codigo>', views.editincome),
    path('editarincome/<codigo>', views.editarincome),
    path('registerspents/', views.registerspents),
    path('spent/deletespent/<codigo>', views.deletespent),
    path('spent/editspent/<codigo>', views.editspent),
    path('editarspent/<codigo>', views.editarspent),
    path('estadis/', views.estadis, name = 'estadis'),
    path('notifications/',views.notifications),
    path('feed/notifications/',views.notifications),
    path('', views.home),
    path('advices/',views.advices),
    path('notifications/advices/',views.advices),
    path('feed/notifications/advices', views.advices),
    path('feed/notifications/add_Reminder', views.add_Reminder),
    path('feed/notifications/see_Reminder', views.see_Reminder),
    path('feed/notifications/reminders/add_Reminder', views.add_Reminder),
    path('feed/notifications/reminders/see_Reminder', views.see_Reminder),
    path('home/feed/notifications/advices', views.advices),
    path('movements/', views.movements),
    path('reports/',views.reports),
    path('goals/', views.goal_view, name = 'goal'),
    path('registergoals/', views.registergoals),
    path('goals/deletegoal/<codigo>', views.deletegoal),
    path('goals/editgoal/<codigo>', views.editgoal),
    path('editargoal/<codigo>', views.editargoal),
    path('dues/', views.due_view, name = 'due'),
    path('registerdues/', views.registerdues),
    path('dues/deletedue/<codigo>', views.deletedue),
    path('dues/editdue/<codigo>', views.editdue),
    path('editardue/<codigo>', views.editardue),
    path('reminders/', views.reminder_view, name = 'reminder'),
    path('registerreminders/', views.registerreminders),
    path('reminders/deletereminder/<codigo>', views.deletereminder),
    path('reminders/editreminder/<codigo>', views.editreminder),
    path('editarreminder/<codigo>', views.editarreminder),
    path('admin/', admin.site.urls),
    path('signin/',views.signin, name='signin'),
    path('signout/',views.signout, name='signout'),
    path('signup/',views.signup, name='signup'),
    path('getadvice/',views.getadvice),
]   



