# Generated by Django 4.0.6 on 2022-11-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_income_type_income_alter_income_date_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='spent',
            name='type_spent',
            field=models.CharField(default='', max_length=200),
        ),
    ]
