# Generated by Django 4.0.6 on 2022-11-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_spent_type_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_goal', models.CharField(max_length=50)),
                ('value_goal', models.IntegerField(default=0)),
                ('date_goal', models.DateField(verbose_name='Goal date.')),
            ],
        ),
    ]
