# Generated by Django 4.0.6 on 2022-09-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_income_id_income_income_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='income_id',
        ),
        migrations.AddField(
            model_name='income',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
