# Generated by Django 4.0.6 on 2022-11-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reminder', models.CharField(max_length=50)),
                ('date_due', models.DateField(verbose_name='Due date.')),
                ('remember_reminder', models.IntegerField(default=0)),
                ('detail_due', models.DateField(max_length=200)),
            ],
        ),
    ]
